import type { INodeProperties } from 'n8n-workflow';

export const envelopeOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['envelope'] } },
		options: [
			{ name: 'Create', value: 'create', action: 'Create a multi-signer envelope' },
			{ name: 'Get', value: 'get', action: 'Get envelope details' },
			{ name: 'Add Session', value: 'addSession', action: 'Add a signing session to an envelope' },
			{ name: 'Combined Stamp', value: 'combinedStamp', action: 'Generate combined stamped PDF' },
		],
		default: 'create',
	},
];

export const envelopeFields: INodeProperties[] = [
	{
		displayName: 'Envelope ID',
		name: 'envelopeId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['envelope'], operation: ['get', 'addSession', 'combinedStamp'] } },
	},
	{
		displayName: 'Signing Mode',
		name: 'signingMode',
		type: 'options',
		default: 'PARALLEL',
		options: [
			{ name: 'Parallel (all signers at once)', value: 'PARALLEL' },
			{ name: 'Sequential (one after another)', value: 'SEQUENTIAL' },
		],
		displayOptions: { show: { resource: ['envelope'], operation: ['create'] } },
	},
	{
		displayName: 'Total Signers',
		name: 'totalSigners',
		type: 'number',
		default: 2,
		typeOptions: { minValue: 2, maxValue: 50 },
		required: true,
		displayOptions: { show: { resource: ['envelope'], operation: ['create'] } },
	},
	{
		displayName: 'Document Source',
		name: 'documentSource',
		type: 'options',
		default: 'binary',
		options: [
			{ name: 'Binary Property (from previous node)', value: 'binary' },
			{ name: 'Base64 String', value: 'base64' },
		],
		displayOptions: { show: { resource: ['envelope'], operation: ['create'] } },
	},
	{
		displayName: 'Binary Property',
		name: 'binaryProperty',
		type: 'string',
		default: 'data',
		displayOptions: { show: { resource: ['envelope'], operation: ['create'], documentSource: ['binary'] } },
	},
	{
		displayName: 'Document Content (Base64)',
		name: 'documentContent',
		type: 'string',
		typeOptions: { rows: 3 },
		default: '',
		displayOptions: { show: { resource: ['envelope'], operation: ['create'], documentSource: ['base64'] } },
	},
	{
		displayName: 'Filename',
		name: 'filename',
		type: 'string',
		default: 'document.pdf',
		displayOptions: { show: { resource: ['envelope'], operation: ['create'] } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['envelope'], operation: ['create'] } },
		options: [
			{ displayName: 'Return URL', name: 'returnUrl', type: 'string', default: '' },
			{ displayName: 'Cancel URL', name: 'cancelUrl', type: 'string', default: '' },
			{
				displayName: 'Locale',
				name: 'locale',
				type: 'options',
				default: 'pt-BR',
				options: [
					{ name: 'Portuguese (Brasil)', value: 'pt-BR' },
					{ name: 'English', value: 'en' },
					{ name: 'Spanish', value: 'es' },
				],
			},
			{ displayName: 'Expires In (Minutes)', name: 'expiresInMinutes', type: 'number', default: 1440 },
			{ displayName: 'Metadata (JSON)', name: 'metadata', type: 'json', default: '{}' },
			{ displayName: 'Idempotency Key', name: 'idempotencyKey', type: 'string', default: '' },
		],
	},
	{
		displayName: 'Signer Index',
		name: 'signerIndex',
		type: 'number',
		default: 0,
		required: true,
		description: 'Zero-based position of this signer in the envelope',
		displayOptions: { show: { resource: ['envelope'], operation: ['addSession'] } },
	},
	{
		displayName: 'Signer Name',
		name: 'signerName',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['envelope'], operation: ['addSession'] } },
	},
	{
		displayName: 'Signer External ID',
		name: 'signerExternalId',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['envelope'], operation: ['addSession'] } },
	},
	{
		displayName: 'Policy Profile',
		name: 'policyProfile',
		type: 'options',
		default: 'CLICK_ONLY',
		options: [
			{ name: 'Click Only', value: 'CLICK_ONLY' },
			{ name: 'OTP', value: 'OTP' },
			{ name: 'Biometric', value: 'BIOMETRIC' },
			{ name: 'Click + OTP', value: 'CLICK_AND_OTP' },
			{ name: 'Click + Biometric', value: 'CLICK_AND_BIOMETRIC' },
			{ name: 'Full', value: 'FULL' },
			{ name: 'Digital Certificate', value: 'DIGITAL_CERT' },
		],
		displayOptions: { show: { resource: ['envelope'], operation: ['addSession'] } },
	},
	{
		displayName: 'Additional Signer Fields',
		name: 'additionalSignerFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['envelope'], operation: ['addSession'] } },
		options: [
			{ displayName: 'Signer Email', name: 'signerEmail', type: 'string', default: '' },
			{ displayName: 'Signer Phone', name: 'signerPhone', type: 'string', default: '' },
			{ displayName: 'Signer CPF', name: 'signerCpf', type: 'string', default: '' },
			{ displayName: 'Signer CNPJ', name: 'signerCnpj', type: 'string', default: '' },
			{ displayName: 'Signer Birth Date', name: 'signerBirthDate', type: 'string', default: '' },
			{
				displayName: 'OTP Channel',
				name: 'otpChannel',
				type: 'options',
				default: 'email',
				options: [
					{ name: 'Email', value: 'email' },
					{ name: 'SMS', value: 'sms' },
				],
			},
			{ displayName: 'Return URL', name: 'returnUrl', type: 'string', default: '' },
			{ displayName: 'Cancel URL', name: 'cancelUrl', type: 'string', default: '' },
			{ displayName: 'Metadata (JSON)', name: 'metadata', type: 'json', default: '{}' },
		],
	},
];
