import type { INodeProperties } from 'n8n-workflow';

export const signingSessionOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['signingSession'] } },
		options: [
			{ name: 'Create', value: 'create', action: 'Create a signing session', description: 'Create a new signing session and return its URL' },
			{ name: 'Get Status', value: 'getStatus', action: 'Get signing session status' },
			{ name: 'Cancel', value: 'cancel', action: 'Cancel a signing session' },
			{ name: 'Wait for Completion', value: 'waitForCompletion', action: 'Poll until session reaches a terminal state' },
		],
		default: 'create',
	},
];

export const signingSessionFields: INodeProperties[] = [
	{
		displayName: 'Session ID',
		name: 'sessionId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: { show: { resource: ['signingSession'], operation: ['getStatus', 'cancel', 'waitForCompletion'] } },
	},
	{
		displayName: 'Purpose',
		name: 'purpose',
		type: 'options',
		default: 'DOCUMENT_SIGNATURE',
		options: [
			{ name: 'Document Signature', value: 'DOCUMENT_SIGNATURE' },
			{ name: 'Action Authentication', value: 'ACTION_AUTHENTICATION' },
		],
		displayOptions: { show: { resource: ['signingSession'], operation: ['create'] } },
	},
	{
		displayName: 'Policy Profile',
		name: 'policyProfile',
		type: 'options',
		default: 'CLICK_ONLY',
		options: [
			{ name: 'Click Only (clickwrap)', value: 'CLICK_ONLY' },
			{ name: 'OTP (Email or SMS)', value: 'OTP' },
			{ name: 'Biometric (Facial)', value: 'BIOMETRIC' },
			{ name: 'Click + OTP', value: 'CLICK_AND_OTP' },
			{ name: 'Click + Biometric', value: 'CLICK_AND_BIOMETRIC' },
			{ name: 'OTP + Biometric', value: 'OTP_AND_BIOMETRIC' },
			{ name: 'Full (Click + OTP + Biometric)', value: 'FULL' },
			{ name: 'Digital Certificate (ICP-Brasil)', value: 'DIGITAL_CERT' },
			{ name: 'Custom', value: 'CUSTOM' },
		],
		displayOptions: { show: { resource: ['signingSession'], operation: ['create'] } },
	},
	{
		displayName: 'Signer Name',
		name: 'signerName',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['signingSession'], operation: ['create'] } },
	},
	{
		displayName: 'Signer External ID',
		name: 'signerExternalId',
		type: 'string',
		default: '',
		required: true,
		description: 'Your system\'s identifier for this signer (e.g., user ID). Used for audit trails.',
		displayOptions: { show: { resource: ['signingSession'], operation: ['create'] } },
	},
	{
		displayName: 'Document Source',
		name: 'documentSource',
		type: 'options',
		default: 'binary',
		options: [
			{ name: 'Binary Property (from previous node)', value: 'binary' },
			{ name: 'Base64 String', value: 'base64' },
			{ name: 'None (ACTION_AUTHENTICATION only)', value: 'none' },
		],
		displayOptions: { show: { resource: ['signingSession'], operation: ['create'] } },
	},
	{
		displayName: 'Binary Property',
		name: 'binaryProperty',
		type: 'string',
		default: 'data',
		description: 'Name of the binary property containing the document',
		displayOptions: { show: { resource: ['signingSession'], operation: ['create'], documentSource: ['binary'] } },
	},
	{
		displayName: 'Document Content (Base64)',
		name: 'documentContent',
		type: 'string',
		typeOptions: { rows: 3 },
		default: '',
		displayOptions: { show: { resource: ['signingSession'], operation: ['create'], documentSource: ['base64'] } },
	},
	{
		displayName: 'Filename',
		name: 'filename',
		type: 'string',
		default: 'document.pdf',
		displayOptions: { show: { resource: ['signingSession'], operation: ['create'], documentSource: ['binary', 'base64'] } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['signingSession'], operation: ['create'] } },
		options: [
			{ displayName: 'Signer Email', name: 'signerEmail', type: 'string', default: '', placeholder: 'user@example.com' },
			{ displayName: 'Signer Phone', name: 'signerPhone', type: 'string', default: '', placeholder: '+5511999999999' },
			{ displayName: 'Signer CPF', name: 'signerCpf', type: 'string', default: '' },
			{ displayName: 'Signer CNPJ', name: 'signerCnpj', type: 'string', default: '' },
			{ displayName: 'Signer Birth Date', name: 'signerBirthDate', type: 'string', default: '', placeholder: 'YYYY-MM-DD' },
			{
				displayName: 'OTP Channel',
				name: 'otpChannel',
				type: 'options',
				default: 'email',
				options: [
					{ name: 'Email', value: 'email' },
					{ name: 'SMS', value: 'sms' },
				],
			},
			{ displayName: 'Return URL', name: 'returnUrl', type: 'string', default: '' },
			{ displayName: 'Cancel URL', name: 'cancelUrl', type: 'string', default: '' },
			{
				displayName: 'Locale',
				name: 'locale',
				type: 'options',
				default: 'pt-BR',
				options: [
					{ name: 'Portuguese (Brasil)', value: 'pt-BR' },
					{ name: 'English', value: 'en' },
					{ name: 'Spanish', value: 'es' },
				],
			},
			{ displayName: 'Expires In (Minutes)', name: 'expiresInMinutes', type: 'number', default: 60 },
			{
				displayName: 'Metadata (JSON)',
				name: 'metadata',
				type: 'json',
				default: '{}',
				description: 'Key-value pairs with string values',
			},
			{ displayName: 'Action Type', name: 'actionType', type: 'string', default: '', description: 'For ACTION_AUTHENTICATION purpose' },
			{ displayName: 'Action Description', name: 'actionDescription', type: 'string', default: '' },
			{ displayName: 'Action Reference', name: 'actionReference', type: 'string', default: '' },
			{ displayName: 'Idempotency Key', name: 'idempotencyKey', type: 'string', default: '' },
		],
	},
	{
		displayName: 'Poll Interval (Ms)',
		name: 'pollIntervalMs',
		type: 'number',
		default: 3000,
		displayOptions: { show: { resource: ['signingSession'], operation: ['waitForCompletion'] } },
	},
	{
		displayName: 'Timeout (Ms)',
		name: 'timeoutMs',
		type: 'number',
		default: 300000,
		displayOptions: { show: { resource: ['signingSession'], operation: ['waitForCompletion'] } },
	},
];
